services:
  postgres:
    container_name: database
    image: cleisonfmelo/postgres-pg-cron:latest
    env_file: .env
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    shm_size: 4gb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: 200m

  redis:
    container_name: redis
    image: redis:6.2-alpine
    env_file: .env
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    logging:
      options:
        max-size: 200m

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - '${BACKEND_PORT:-8000}:8000'
    depends_on:
      - postgres
      - redis

volumes:
  redis_data:
    driver: local

  postgres_data:
    driver: local
